#include "DataManagerTest.h"
#include "MarketEngineTest.h"
#include "PortfolioTest.h"
#include "StrategyTest.h"
#include "TransactionsTypeTest.h"
#include "TesterTest.h"
#include "DataLogTest.h"
